services:
  app:
    container_name: nestjs_app
    build: .
    env_file:
      - .env
    command: ['npm', 'run', 'start:dev']
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
    networks:
      - app_network

  mongo:
    container_name: nestjs_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - app_network

  mongo-express:
    container_name: nestjs_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app_network

#Volumes
volumes:
  node_modules:
    driver: local

networks:
  app_network:
    external: true
